# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
name: Barry McGee
job_title: Front End Developer
email: hello@barrymcgee.co.uk
description: > # this means to ignore newlines until "baseurl:"
  I'm a Front End Developer - based in London, England.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.barrymcgee.co.uk" # the base hostname & protocol for your site
twitter_username: barrymcgee
github_username:  barrymcgee

# Build settings
markdown: kramdown

# only build incrementally
incremental: true

# next available for new work
next_up: 4th April 2016
